# Generated by Django 4.0.6 on 2022-07-14 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prev_text',
            field=models.TextField(default=datetime.datetime(2022, 7, 14, 8, 6, 49, 935382, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
